### ISSUE TITLE
Error when updating CiviCRM on Wordpress

### ISSUE THREAD

**Issue by themak1985** [civicrm/org.civicrm.flexmailer#27]
As reported on [this stack exchange](https://civicrm.stackexchange.com/questions/25868/system-status-page-error-after-5-3-1-upgrade)

When upgrading versions of CiviCRM - viewing the system status page - I get the following error:

`Sorry, due to an error, we are unable to fulfill your request at the moment. You may want to contact your administrator or service provider with more details about what action you were performing when this occurred. You have requested a non-existent service "civi_flexmailer_required_tokens".`

This happened when updating from 5.3 - 5.3.1 and also 5.3.1 - 5.6

Simple fix is to disable flexmailer (and mosaico as necessary) and re-enable.  However I thought I would share.

**Comment by MegaphoneJon** [comment]
Clearing cache also solves this. I know some cache clearing was recently added to the update process, which is why I haven't dug into this deeper, but if it's still happening on 5.6 upgrades it's probably worth figuring out if we're not clearing every cache that we could.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by themak1985** [comment]
I think I have cleared every cache I can think of. This is obviously low priority - as its an easy fix - but i still have to disable - enable. 
![flexmailer](https://user-images.githubusercontent.com/28904266/48448351-c60c9e00-e76c-11e8-8307-e4f867ea3199.PNG)

**Comment by mwestergaard** [comment]
Just ran into this issue with upgrade from 5.8.2 to 5.9. The upgrade went fine on my dev box. When applied to my production box, the upgrade reported 'Exception: "Queue runner must be configured before execution. - onEnd"'. The status footer showed "Powered by CiviCRM 5.9.0", but selecting the System Status option returned the message described here.

I cleared cache from Christian Wach's CiviCRM Admin Utilities plugin and also tried "cv flush" with no effect. I disabled/enabled the Mosaico and Flexmailer extensions as described here, and that lets the System Status function run, but it still reports a warning that an the 5.9.0 upgrade is available. Despite the warning, things seem to be okay, but I'm not sure there aren't upgrade activities that weren't performed.

**Comment by mlutfy** [comment]
Related: #45 

Has anyone run into this issue recently? I think it has been fixed a few months ago.

**Comment by mlutfy** [comment]
(Closing for now, feel free to re-open if necessary)

**Comment by leanwebstart** [comment]
Having same issue trying to upgrade to 5.27.3 ... I don't have any extensions installed... cleared civicrm cache... no luck...still does not work.
